"""ConstraintContextManager — per-task-id runtime state for constraint enforcement."""

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Optional

from src.constraint.types import Constraint, ConstraintContext, ConstraintResult
from src.logger import logger


class _SessionState:
    """Mutable state tracked for one task_id."""

    __slots__ = ("constraints", "agent_name", "started_at", "tokens_used")

    def __init__(self, constraints: List[Constraint], agent_name: str) -> None:
        self.constraints = constraints
        self.agent_name = agent_name
        self.started_at = datetime.now()
        self.tokens_used: int = 0


class ConstraintContextManager:
    """Manages per-task constraint sessions and enforcement.

    All state is keyed by task_id, matching the identifier used throughout
    the agent loop (generated by make_id() in each agent's __call__).
    """

    def __init__(self) -> None:
        self._sessions: Dict[str, _SessionState] = {}

    # ------------------------------------------------------------------
    # Session lifecycle
    # ------------------------------------------------------------------

    def start_session(
        self,
        task_id: str,
        constraints: List[Constraint],
        agent_name: str,
    ) -> None:
        """Register a new task session. Called automatically on the first step."""
        self._sessions[task_id] = _SessionState(constraints, agent_name)
        logger.debug(
            f"| 🔒 ConstraintContextManager: session started "
            f"task_id={task_id} agent={agent_name} "
            f"constraints={[c.name for c in constraints]}"
        )

    def has_session(self, task_id: str) -> bool:
        return task_id in self._sessions

    def end_session(self, task_id: str) -> None:
        """Remove session state. Called automatically when the task finishes."""
        self._sessions.pop(task_id, None)

    # ------------------------------------------------------------------
    # State updates
    # ------------------------------------------------------------------

    def record_tokens(self, task_id: str, tokens: int) -> None:
        """Accumulate token usage for this task. Called after each model call."""
        state = self._sessions.get(task_id)
        if state:
            state.tokens_used += tokens

    # ------------------------------------------------------------------
    # Constraint check
    # ------------------------------------------------------------------

    async def check(
        self,
        task_id: str,
        step_number: int,
    ) -> Optional[ConstraintResult]:
        """Check all enabled constraints for the given task.

        Returns the first violated ConstraintResult, or None if all pass.
        """
        state = self._sessions.get(task_id)
        if not state or not state.constraints:
            return None

        elapsed = (datetime.now() - state.started_at).total_seconds()
        ctx = ConstraintContext(
            task_id=task_id,
            agent_name=state.agent_name,
            step_number=step_number,
            tokens_used=state.tokens_used,
            elapsed_sec=elapsed,
        )

        for constraint in state.constraints:
            if not constraint.enabled:
                continue
            result = await constraint.check(ctx)
            if result.violated:
                logger.warning(
                    f"| 🚫 Constraint violated [{state.agent_name}] "
                    f"task_id={task_id}: {result.reason}"
                )
                return result

        return None
