general_agent = dict(
    base_dir = "work_dir/general_agent",
    name = "general_agent",
    type = "Agent",
    description = "An iterative agent that reasons and acts by using tools, skills, and direct responses to accomplish tasks accurately, safely, and efficiently.",
    model_name = "aws_claude/claude-opus-4.8",
    prompt_name = "general_agent",
    memory_name = "file_system_memory",
    max_actions = 10,
    max_step = 50,
    max_token = 1000000,
    timeout = 1800,
    review_steps = 5,
    log_max_length = 1000,
    require_grad = False,
    use_memory = False,
)
