optimize_agent = dict(
    name="optimize_agent",
    type="OptimizeAgent",
    description="Improves an existing component of any type from execution evidence, then re-registers it.",
    model_name="llm_hub/claude-opus-5",
    prompt_name="optimize_agent",
    memory_name="file_system_memory",
    max_actions=10,
    max_step=30,
    max_token=100_000_000,
    timeout=1800,
    review_steps=5,
    enable_evolving=False,
    use_memory=True,
)
