reason_act_agent = dict(
    base_dir = "work_dir/reason_act_agent",
    name = "reason_act_agent",
    type = "Agent",
    description = "An iterative agent that reasons and acts by using tools, skills, and direct responses to accomplish tasks accurately, safely, and efficiently.",
    model_name = "openai/o3",
    prompt_name = "reason_act_agent",
    memory_name = "file_system_memory",
    max_actions = 10,
    max_step = 50,
    review_steps = 5,
    log_max_length = 1000,
    require_grad = False,
    use_memory = False,
)
