tool_evaluate_agent = dict(
    name="tool_evaluate_agent",
    type="ToolEvaluateAgent",
    description="An agent that evaluates tool behavior given an evaluation task.",
    model_name="aws_claude/claude-opus-4.8",
    prompt_name="tool_evaluate_agent",
    memory_name="file_system_memory",
    max_actions=10,
    max_step=20,
    max_token=1000000,
    timeout=1800,
    review_steps=5,
    require_grad=False,
    permission_mode="read_only",
    use_memory=True,
)
