#!/usr/bin/env python3
"""Write `docs/tool-catalog.md` from the tools the registry actually holds.

A tool's name, description, permission mode and parameter list are spread over a class
body, its `guidance` / `examples` fields, and the `__call__` signature the model's
arguments are bound to. Only the last one decides what a call does, and it is the one nobody reads.
So this generator imports the tool package and reads the live objects — the registry's
`name`, the instance's `permission_mode`, the real signature — instead of parsing the
prose beside them. A hand-written catalog would be a fourth copy of the same facts and
would start rotting the day a parameter is renamed.

    scripts/gen_tool_catalog.py             # rewrite docs/tool-catalog.md
    scripts/gen_tool_catalog.py --check     # print the drift and exit 1
    scripts/gen_tool_catalog.py --inventory # what one fresh import registers, as JSON

`tests/test_tool_catalog.py` makes the same comparison, so a committed catalog that no
longer matches the code fails the suite rather than sitting there wrong. It reads
`--inventory` from a subprocess rather than importing this module, because which tools the
registry holds depends on what else the calling process imported.

The completeness guard is the other half. Registering a tool means writing a class AND
importing it somewhere; a class whose module nothing imports is never registered, and the
catalog would simply not mention it — the quietest possible failure. So the source tree is
scanned for `@TOOL.register_module` classes and compared with what the import produced.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import inspect
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
TOOL_ROOT = ROOT / "agentevolver" / "tool"
CATALOG = ROOT / "docs" / "tool-catalog.md"


class DiscoveryError(RuntimeError):
    """The registry and the source tree disagree, so no catalog can be written.

    Its own exception rather than `SystemExit`: the test suite calls the same functions,
    and a `SystemExit` there is reported as an error with the message buried, which is the
    opposite of what a guard is for.
    """

#: Repeated in the file itself so a reader who arrives via the document, rather than via
#: this script, is told before they start editing it by hand.
HEADER = (
    "<!-- Generated by scripts/gen_tool_catalog.py — do not edit by hand.\n"
    "     Run `python scripts/gen_tool_catalog.py` to regenerate.\n"
    "     tests/test_tool_catalog.py regenerates it and fails when this file drifts. -->\n"
)

PREAMBLE = """\
# Tool Catalog

Every tool the `TOOL` registry holds after `import agentevolver.tool`: the name the model
calls, the description it is offered, the parameters its `__call__` accepts, and the
permission mode the permission manager registers for it.

This page is generated by importing the tool package and reading the live objects, not by
parsing prose beside them. The signature is the only
copy that decides what a call does; the prose is a fourth-hand account of it, and the two
have drifted before. The full guidance text is deliberately not reproduced here — an
agent fetches it on demand through `inspect_capability_tool`, and copying it would add one more place
to keep in step.

Scope: classes carrying `@TOOL.register_module` under `agentevolver/tool/`. Tools generated
at runtime under `extension/` are absent by construction — they do not exist until an
evolution round creates them. A tool whose module exists but which nothing imports is not
absent quietly: the generator's completeness guard fails on it.

Types and defaults are shown as written in the signature. A parameter with no default is
required; the model must send it. "Mutates" is the tool's own `mutates` declaration —
`yes`, `no`, or "not declared", which is the default and means nobody has said either way.
"""


# --------------------------------------------------------------------------- #
# Discovery
# --------------------------------------------------------------------------- #
def declared_tool_classes() -> Dict[str, str]:
    """Every `@TOOL.register_module` class in the source tree, mapped to its module.

    Read from the AST, on purpose: this is the half of the comparison that must not
    depend on the import succeeding. If both sides were taken from the registry, a module
    that nothing imports would be missing from both and the guard would agree with itself.
    """
    declared: Dict[str, str] = {}
    for path in sorted(TOOL_ROOT.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            for decorator in node.decorator_list:
                target = decorator.func if isinstance(decorator, ast.Call) else decorator
                if (isinstance(target, ast.Attribute)
                        and target.attr == "register_module"
                        and isinstance(target.value, ast.Name)
                        and target.value.id == "TOOL"):
                    declared[node.name] = str(path.relative_to(ROOT))
    return declared


def registered_tool_classes() -> Dict[str, type]:
    """Every tool class the registry holds once the package has been imported."""
    import agentevolver.tool  # noqa: F401  (the import is the registration)
    from agentevolver.registry import TOOL

    return dict(TOOL._module_dict)


def completeness_gap() -> List[str]:
    """Classes written as tools that importing the package does not register.

    The four-place registration problem, seen from the end that actually matters: the
    class exists, the export was forgotten, and the running agent is simply never offered
    the tool. Nothing raises — the tool is missing the way a tool the model chose not to
    call is missing.
    """
    declared = declared_tool_classes()
    registered = registered_tool_classes()
    return sorted(
        f"{name} ({module}) is declared with @TOOL.register_module but is not in the "
        f"registry after `import agentevolver.tool`; nothing imports its module"
        for name, module in declared.items() if name not in registered
    )


# --------------------------------------------------------------------------- #
# Reading one tool
# --------------------------------------------------------------------------- #
def _type_name(annotation: Any) -> str:
    """The annotation as written, with `typing.` noise and `<class '...'>` removed.

    Modules differ on `from __future__ import annotations`, so half the signatures arrive
    as strings and half as objects. Both are rendered the same way; otherwise the catalog
    would say `Optional[str]` for one tool and `typing.Optional[str]` for its neighbour
    for a reason no reader could see.
    """
    if annotation is inspect.Parameter.empty:
        return ""
    text = annotation if isinstance(annotation, str) else str(annotation)
    text = re.sub(r"<class '([^']+)'>", r"\1", text)
    return re.sub(r"\btyping\.", "", text)


def parameters_of(instance: Any) -> List[Tuple[str, str, str]]:
    """`(name, type, default)` for each argument the model may send.

    `self`, `*args` and `**kwargs` are dropped: `**kwargs` carries the call context the
    runtime injects, which is not something a model chooses.
    """
    rows: List[Tuple[str, str, str]] = []
    for name, param in inspect.signature(instance.__call__).parameters.items():
        if name in ("self", "kwargs") or param.kind in (
                inspect.Parameter.VAR_KEYWORD, inspect.Parameter.VAR_POSITIONAL):
            continue
        default = "" if param.default is inspect.Parameter.empty else repr(param.default)
        rows.append((name, _type_name(param.annotation), default))
    return rows


def _cell(text: str) -> str:
    """A value safe to drop into a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def instantiate(name: str, cls: type) -> Any:
    """Build one tool the way the tool manager builds it — with no arguments.

    A tool that cannot be constructed bare cannot be constructed by discovery either, so
    failing here is the same failure the runtime would hit, found earlier and with the
    class named.
    """
    try:
        return cls()
    except Exception as error:                                       # noqa: BLE001
        raise DiscoveryError(
            f"{name} cannot be instantiated with no arguments, which is how tool "
            f"discovery builds it: {error!r}") from error


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def render() -> str:
    """The whole document, ordered by the name the model calls.

    Renders what the registry holds and nothing else. The completeness guard is applied
    by `main()` before writing, not here: a rendering function that refuses to run turns
    one red result — "a tool class is unreachable" — into a red result for every check
    that renders, all of them reporting the same thing in a less useful way.
    """
    tools = []
    for class_name, cls in registered_tool_classes().items():
        instance = instantiate(class_name, cls)
        tools.append((instance.name, class_name, cls, instance))
    tools.sort()

    lines = [HEADER, PREAMBLE, "## Summary", "",
             "| Tool | Permission | Mutates | Class | Module |",
             "| --- | --- | --- | --- | --- |"]
    for name, class_name, cls, instance in tools:
        mutates = {True: "yes", False: "no", None: "not declared"}[instance.mutates]
        # The heading is `## \`name\``; GitHub drops the backticks and keeps the
        # underscores, so the anchor is the tool name unchanged.
        lines.append(f"| [`{name}`](#{name}) "
                     f"| `{instance.permission_mode}` | {mutates} "
                     f"| `{class_name}` | `{cls.__module__}` |")

    lines += ["", f"{len(tools)} tools.", ""]

    for name, class_name, cls, instance in tools:
        lines += [f"## `{name}`", "", _cell(instance.description), ""]
        facts = [f"Permission mode: `{instance.permission_mode}`"]
        if instance.mutates is None:
            facts.append("does not declare whether it changes state")
        else:
            facts.append("changes state" if instance.mutates else "reports only")
        if instance.call_timeout_seconds is not None:
            facts.append(f"call budget {instance.call_timeout_seconds:g}s")
        lines += [" · ".join(facts), ""]

        rows = parameters_of(instance)
        if rows:
            lines += ["| Parameter | Type | Required | Default |",
                      "| --- | --- | --- | --- |"]
            for param, type_name, default in rows:
                required = "yes" if default == "" else "no"
                lines.append(f"| `{param}` | `{_cell(type_name) or '—'}` | {required} "
                             f"| {'—' if default == '' else '`' + _cell(default) + '`'} |")
        else:
            lines.append("Takes no arguments.")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def inventory() -> Dict[str, Any]:
    """Everything one fresh `import agentevolver.tool` produces, as plain data.

    This exists so a caller can ask the question in a process of its own. Which tools the
    registry holds depends on what else has been imported, and inside a test session that
    is whatever the other test modules happened to pull in — a module nothing in the
    package imports still registers if one test file imports it directly. Asked in-process,
    "what does importing the package give you" would answer differently depending on which
    tests ran before, which is how a check starts failing only in full runs.
    """
    tools = {}
    for class_name, cls in registered_tool_classes().items():
        instance = instantiate(class_name, cls)
        tools[class_name] = {
            "name": instance.name,
            "module": cls.__module__,
            "permission_mode": instance.permission_mode,
            "instruction": instance.guidance or instance.instruction or "",
            "parameters": [name for name, _, _ in parameters_of(instance)],
        }
    return {"gap": completeness_gap(), "catalog": render(), "tools": tools}


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #
def drift() -> str:
    """The diff between the committed catalog and what the code says today.

    Empty means they agree. The diff is returned rather than printed so the test can put
    it in the failure message — a check that says only "the catalog is stale" sends the
    reader back to run the generator to find out what changed.
    """
    generated = render()
    committed = CATALOG.read_text(encoding="utf-8") if CATALOG.exists() else ""
    if committed == generated:
        return ""
    return "".join(difflib.unified_diff(
        committed.splitlines(keepends=True), generated.splitlines(keepends=True),
        fromfile=f"{_display(CATALOG)} (committed)", tofile="generated"))


def _display(path: Path) -> str:
    """A path to print. Repository-relative when it is inside the repository.

    `relative_to` raises for anything outside, and the test that proves this comparison
    can fail points it at a temporary file — a crash there would be reported as "the
    stale-catalog check is broken" when the check itself is fine.
    """
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="Report drift and exit 1 instead of rewriting the file.")
    parser.add_argument("--inventory", action="store_true",
                        help="Print what one fresh import registers, as JSON, and exit.")
    args = parser.parse_args()

    try:
        return _run(args)
    except DiscoveryError as error:
        print(f"gen_tool_catalog: {error}", file=sys.stderr)
        return 1


def _run(args: argparse.Namespace) -> int:
    if args.inventory:
        print(json.dumps(inventory(), indent=1))
        return 0

    # Before anything is written or compared: a catalog that silently omits a tool
    # somebody wrote is the failure this whole file exists to prevent.
    gap = completeness_gap()
    if gap:
        raise DiscoveryError("incomplete discovery:\n  " + "\n  ".join(gap))

    if args.check:
        diff = drift()
        if diff:
            print(diff, end="", file=sys.stderr)
            print(f"\n{_display(CATALOG)} is out of date; run "
                  f"scripts/gen_tool_catalog.py", file=sys.stderr)
            return 1
        print(f"{_display(CATALOG)} matches the registry")
        return 0

    text = render()
    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    changed = not CATALOG.exists() or CATALOG.read_text(encoding="utf-8") != text
    CATALOG.write_text(text, encoding="utf-8")
    print(f"{'wrote' if changed else 'unchanged'}: {_display(CATALOG)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
